### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by danreeves** [MrMicky-FR/XboxAPI-Workers#1]
Hey, are the setup instructions in the README still correct? I tried following them and couldn't get it to work.

I noticed the MS_CLIENT_ID and MS_CLIENT_SECRET and played around with creating an azure app and trying to get the /auth/redirect part working and after some trial and error I got a valid access_token, so my deployment is working now but couldn't find a refresh token so I'm unsure if it's going to remain working 😄 

Any pointers on getting set up correctly would be greatly appreciated. 

Otherwise, how do you feel about others using your deployment (https://xboxapi.mrmicky.workers.dev/)?

**Comment by MrMicky-FR** [comment]
Hi, yes the setup instructions in the README _should_ be correct (but haven't tested them since the initial release), what's the issue you had ?

About `MS_CLIENT_SECRET` and `MS_CLIENT_ID`, it's used only for Xbox OAuth (which isn't relevant for most cases), so the profiles endpoints should work fine without these client credentials
